//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalidadLiberacion
    {
        public int Id { get; set; }
        public int LoteId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public string EvidenciaUrl { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
