//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCheckpointEntities : DbContext
    {
        public BDCheckpointEntities()
            : base("name=BDCheckpointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CalidadLiberacion> CalidadLiberacion { get; set; }
        public DbSet<Lote> Lote { get; set; }
        public DbSet<Movimiento> Movimiento { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Ubicacion> Ubicacion { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
