//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public Lote()
        {
            this.CalidadLiberacion = new HashSet<CalidadLiberacion>();
            this.Movimiento = new HashSet<Movimiento>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public string CodigoLote { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string OrdenCompra { get; set; }
        public string GuiaRecepcion { get; set; }
        public Nullable<decimal> TempIngreso { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<CalidadLiberacion> CalidadLiberacion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
