//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public int LoteId { get; set; }
        public int SedeId { get; set; }
        public Nullable<int> OrigenUbicacionId { get; set; }
        public Nullable<int> DestinoUbicacionId { get; set; }
        public string Tipo { get; set; }
        public decimal Cantidad { get; set; }
        public string Unidad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public string Motivo { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
