//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Lote = new HashSet<Lote>();
        }
    
        public int Id { get; set; }
        public string Sku { get; set; }
        public string Nombre { get; set; }
        public string Unidad { get; set; }
        public int VidaUtilDias { get; set; }
        public Nullable<decimal> TempMin { get; set; }
        public Nullable<decimal> TempMax { get; set; }
        public decimal StockMinimo { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Lote> Lote { get; set; }
    }
}
