//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public int LoteId { get; set; }
        public int UbicacionId { get; set; }
        public decimal Cantidad { get; set; }
        public string Unidad { get; set; }
        public System.DateTime ActualizadoEn { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
