//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.Movimiento = new HashSet<Movimiento>();
            this.Movimiento1 = new HashSet<Movimiento>();
            this.Stock = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public int SedeId { get; set; }
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Capacidad { get; set; }
    
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<Movimiento> Movimiento1 { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
