//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckpointSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.CalidadLiberacion = new HashSet<CalidadLiberacion>();
            this.Movimiento = new HashSet<Movimiento>();
            this.UserRole = new HashSet<UserRole>();
            this.UserRole1 = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<CalidadLiberacion> CalidadLiberacion { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<UserRole> UserRole1 { get; set; }
    }
}
